### ISSUE TITLE
Formatear ruts en la vista

### ISSUE THREAD

**Issue by CafeLucuma** [FeloVilches/Monitor-Transacciones-Pingeso#1]
para que no salgan con un 0 a la izquierda. Agregarlo en Helper.java

f. vilches

**Comment by FeloVilches** [comment]
Listo, lo puse como Helper en el frontend (Javascript), y tambien hice que dataTables pasara ese dato por la funcion.

https://github.com/FeloVilches/Monitor-Transacciones-Pingeso/blob/master/src/main/webapp/resources/js/main.js#L14
